//
// Copyright (c) ZeroC, Inc. All rights reserved.
//
//
// Ice version 3.7.10
//
// <auto-generated>
//
// Generated from file `Player.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

/* eslint-disable */
/* jshint ignore: start */

(function(module, require, exports)
{
    const Ice = require("ice").Ice;
    const _ModuleRegistry = Ice._ModuleRegistry;
    const Slice = Ice.Slice;

    let Demo = _ModuleRegistry.module("Demo");

    Slice.defineSequence(Demo, "BytesHelper", "Ice.ByteHelper", true);

    Slice.defineSequence(Demo, "stringSeqHelper", "Ice.StringHelper", false);

    const iceC_Demo_Observer_ids = [
        "::Demo::Observer",
        "::Ice::Object"
    ];

    Demo.Observer = class extends Ice.Object
    {
    };

    Demo.ObserverPrx = class extends Ice.ObjectPrx
    {
    };

    Slice.defineOperations(Demo.Observer, Demo.ObserverPrx, iceC_Demo_Observer_ids, 0,
    {
        "notifyAudio": [, , , , , [["Demo.BytesHelper"]], , , , ],
        "notifyAudioMessage": [, , , , , [["Demo.BytesHelper"]], , , , ],
        "incomingCall": [, , , , , [[7]], , , , ],
        "callAccepted": [, , , , , [[7]], , , , ],
        "callRejected": [, , , , , [[7]], , , , ],
        "CallEnded": [, , , , , [[7]], , , , ]
    });

    const iceC_Demo_Subject_ids = [
        "::Demo::Subject",
        "::Ice::Object"
    ];

    Demo.Subject = class extends Ice.Object
    {
    };

    Demo.SubjectPrx = class extends Ice.ObjectPrx
    {
    };

    Slice.defineOperations(Demo.Subject, Demo.SubjectPrx, iceC_Demo_Subject_ids, 0,
    {
        "attachObserver": [, , , , , [["Demo.ObserverPrx"], [7]], , , , ],
        "sendAudio": [, , , , , [[7], [7], ["Demo.BytesHelper"]], , , , ],
        "sendAudioMessage": [, , , , , [[7], [7], ["Demo.BytesHelper"]], , , , ],
        "getConnectedUsers": [, , , , ["Demo.stringSeqHelper"], , , , , ],
        "startCall": [, , , , [7], [[7], [7]], , , , ],
        "acceptCall": [, , , , , [[7], [7]], , , , ],
        "rejectCall": [, , , , , [[7], [7]], , , , ],
        "endCall": [, , , , , [[7], [7]], , , , ]
    });
    exports.Demo = Demo;
}
(typeof(global) !== "undefined" && typeof(global.process) !== "undefined" ? module : undefined,
 typeof(global) !== "undefined" && typeof(global.process) !== "undefined" ? require :
 (typeof WorkerGlobalScope !== "undefined" && self instanceof WorkerGlobalScope) ? self.Ice._require : window.Ice._require,
 typeof(global) !== "undefined" && typeof(global.process) !== "undefined" ? exports :
 (typeof WorkerGlobalScope !== "undefined" && self instanceof WorkerGlobalScope) ? self : window));
